/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "crash_report.pb-c.h"
void   plcrash__crash_report__init
                     (Plcrash__CrashReport         *message)
{
  static Plcrash__CrashReport init_value = PLCRASH__CRASH_REPORT__INIT;
  *message = init_value;
};
size_t plcrash__crash_report__get_packed_size
                     (const Plcrash__CrashReport *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plcrash__crash_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plcrash__crash_report__pack
                     (const Plcrash__CrashReport *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plcrash__crash_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plcrash__crash_report__pack_to_buffer
                     (const Plcrash__CrashReport *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plcrash__crash_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Plcrash__CrashReport *
       plcrash__crash_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Plcrash__CrashReport *)
     protobuf_c_message_unpack (&plcrash__crash_report__descriptor,
                                allocator, len, data);
}
void   plcrash__crash_report__free_unpacked
                     (Plcrash__CrashReport *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &plcrash__crash_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue plcrash__crash_report__processor__type_encoding__enum_values_by_number[2] =
{
  { "TYPE_ENCODING_UNKNOWN", "PLCRASH__CRASH_REPORT__PROCESSOR__TYPE_ENCODING__TYPE_ENCODING_UNKNOWN", 0 },
  { "TYPE_ENCODING_MACH", "PLCRASH__CRASH_REPORT__PROCESSOR__TYPE_ENCODING__TYPE_ENCODING_MACH", 1 },
};
static const ProtobufCIntRange plcrash__crash_report__processor__type_encoding__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex plcrash__crash_report__processor__type_encoding__enum_values_by_name[2] =
{
  { "TYPE_ENCODING_MACH", 1 },
  { "TYPE_ENCODING_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor plcrash__crash_report__processor__type_encoding__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.Processor.TypeEncoding",
  "TypeEncoding",
  "Plcrash__CrashReport__Processor__TypeEncoding",
  "plcrash",
  2,
  plcrash__crash_report__processor__type_encoding__enum_values_by_number,
  2,
  plcrash__crash_report__processor__type_encoding__enum_values_by_name,
  1,
  plcrash__crash_report__processor__type_encoding__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const Plcrash__CrashReport__Processor__TypeEncoding plcrash__crash_report__processor__encoding__default_value = PLCRASH__CRASH_REPORT__PROCESSOR__TYPE_ENCODING__TYPE_ENCODING_UNKNOWN;
static const ProtobufCFieldDescriptor plcrash__crash_report__processor__field_descriptors[3] =
{
  {
    "encoding",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Processor, has_encoding),
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Processor, encoding),
    &plcrash__crash_report__processor__type_encoding__descriptor,
    &plcrash__crash_report__processor__encoding__default_value,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Processor, type),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "subtype",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Processor, subtype),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__processor__field_indices_by_name[] = {
  0,   /* field[0] = encoding */
  2,   /* field[2] = subtype */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange plcrash__crash_report__processor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__processor__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.Processor",
  "Processor",
  "Plcrash__CrashReport__Processor",
  "plcrash",
  sizeof(Plcrash__CrashReport__Processor),
  3,
  plcrash__crash_report__processor__field_descriptors,
  plcrash__crash_report__processor__field_indices_by_name,
  1,  plcrash__crash_report__processor__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
const ProtobufCEnumValue plcrash__crash_report__system_info__operating_system__enum_values_by_number[4] =
{
  { "MAC_OS_X", "PLCRASH__CRASH_REPORT__SYSTEM_INFO__OPERATING_SYSTEM__MAC_OS_X", 0 },
  { "IPHONE_OS", "PLCRASH__CRASH_REPORT__SYSTEM_INFO__OPERATING_SYSTEM__IPHONE_OS", 1 },
  { "IPHONE_SIMULATOR", "PLCRASH__CRASH_REPORT__SYSTEM_INFO__OPERATING_SYSTEM__IPHONE_SIMULATOR", 2 },
  { "OS_UNKNOWN", "PLCRASH__CRASH_REPORT__SYSTEM_INFO__OPERATING_SYSTEM__OS_UNKNOWN", 3 },
};
static const ProtobufCIntRange plcrash__crash_report__system_info__operating_system__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex plcrash__crash_report__system_info__operating_system__enum_values_by_name[4] =
{
  { "IPHONE_OS", 1 },
  { "IPHONE_SIMULATOR", 2 },
  { "MAC_OS_X", 0 },
  { "OS_UNKNOWN", 3 },
};
const ProtobufCEnumDescriptor plcrash__crash_report__system_info__operating_system__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.SystemInfo.OperatingSystem",
  "OperatingSystem",
  "Plcrash__CrashReport__SystemInfo__OperatingSystem",
  "plcrash",
  4,
  plcrash__crash_report__system_info__operating_system__enum_values_by_number,
  4,
  plcrash__crash_report__system_info__operating_system__enum_values_by_name,
  1,
  plcrash__crash_report__system_info__operating_system__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const Plcrash__CrashReport__SystemInfo__OperatingSystem plcrash__crash_report__system_info__operating_system__default_value = PLCRASH__CRASH_REPORT__SYSTEM_INFO__OPERATING_SYSTEM__OS_UNKNOWN;
static const Plcrash__Architecture plcrash__crash_report__system_info__architecture__default_value = PLCRASH__ARCHITECTURE__ARCHITECTURE_UNKNOWN;
static const ProtobufCFieldDescriptor plcrash__crash_report__system_info__field_descriptors[5] =
{
  {
    "operating_system",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__SystemInfo, has_operating_system),
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__SystemInfo, operating_system),
    &plcrash__crash_report__system_info__operating_system__descriptor,
    &plcrash__crash_report__system_info__operating_system__default_value,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "os_version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__SystemInfo, os_version),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "architecture",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__SystemInfo, architecture),
    &plcrash__architecture__descriptor,
    &plcrash__crash_report__system_info__architecture__default_value,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__SystemInfo, timestamp),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "os_build",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__SystemInfo, os_build),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__system_info__field_indices_by_name[] = {
  2,   /* field[2] = architecture */
  0,   /* field[0] = operating_system */
  4,   /* field[4] = os_build */
  1,   /* field[1] = os_version */
  3,   /* field[3] = timestamp */
};
static const ProtobufCIntRange plcrash__crash_report__system_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__system_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.SystemInfo",
  "SystemInfo",
  "Plcrash__CrashReport__SystemInfo",
  "plcrash",
  sizeof(Plcrash__CrashReport__SystemInfo),
  5,
  plcrash__crash_report__system_info__field_descriptors,
  plcrash__crash_report__system_info__field_indices_by_name,
  1,  plcrash__crash_report__system_info__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plcrash__crash_report__application_info__field_descriptors[2] =
{
  {
    "identifier",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__ApplicationInfo, identifier),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__ApplicationInfo, version),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__application_info__field_indices_by_name[] = {
  0,   /* field[0] = identifier */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange plcrash__crash_report__application_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__application_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.ApplicationInfo",
  "ApplicationInfo",
  "Plcrash__CrashReport__ApplicationInfo",
  "plcrash",
  sizeof(Plcrash__CrashReport__ApplicationInfo),
  2,
  plcrash__crash_report__application_info__field_descriptors,
  plcrash__crash_report__application_info__field_indices_by_name,
  1,  plcrash__crash_report__application_info__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plcrash__crash_report__thread__stack_frame__field_descriptors[1] =
{
  {
    "pc",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Thread__StackFrame, pc),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__thread__stack_frame__field_indices_by_name[] = {
  0,   /* field[0] = pc */
};
static const ProtobufCIntRange plcrash__crash_report__thread__stack_frame__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__thread__stack_frame__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.Thread.StackFrame",
  "StackFrame",
  "Plcrash__CrashReport__Thread__StackFrame",
  "plcrash",
  sizeof(Plcrash__CrashReport__Thread__StackFrame),
  1,
  plcrash__crash_report__thread__stack_frame__field_descriptors,
  plcrash__crash_report__thread__stack_frame__field_indices_by_name,
  1,  plcrash__crash_report__thread__stack_frame__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plcrash__crash_report__thread__register_value__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Thread__RegisterValue, name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Thread__RegisterValue, value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__thread__register_value__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange plcrash__crash_report__thread__register_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__thread__register_value__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.Thread.RegisterValue",
  "RegisterValue",
  "Plcrash__CrashReport__Thread__RegisterValue",
  "plcrash",
  sizeof(Plcrash__CrashReport__Thread__RegisterValue),
  2,
  plcrash__crash_report__thread__register_value__field_descriptors,
  plcrash__crash_report__thread__register_value__field_indices_by_name,
  1,  plcrash__crash_report__thread__register_value__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plcrash__crash_report__thread__field_descriptors[4] =
{
  {
    "thread_number",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Thread, thread_number),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "frames",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Thread, n_frames),
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Thread, frames),
    &plcrash__crash_report__thread__stack_frame__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "crashed",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Thread, crashed),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "registers",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Thread, n_registers),
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Thread, registers),
    &plcrash__crash_report__thread__register_value__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__thread__field_indices_by_name[] = {
  2,   /* field[2] = crashed */
  1,   /* field[1] = frames */
  3,   /* field[3] = registers */
  0,   /* field[0] = thread_number */
};
static const ProtobufCIntRange plcrash__crash_report__thread__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__thread__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.Thread",
  "Thread",
  "Plcrash__CrashReport__Thread",
  "plcrash",
  sizeof(Plcrash__CrashReport__Thread),
  4,
  plcrash__crash_report__thread__field_descriptors,
  plcrash__crash_report__thread__field_indices_by_name,
  1,  plcrash__crash_report__thread__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plcrash__crash_report__binary_image__field_descriptors[5] =
{
  {
    "base_address",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__BinaryImage, base_address),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__BinaryImage, size),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__BinaryImage, name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "uuid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__BinaryImage, has_uuid),
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__BinaryImage, uuid),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "code_type",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__BinaryImage, code_type),
    &plcrash__crash_report__processor__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__binary_image__field_indices_by_name[] = {
  0,   /* field[0] = base_address */
  4,   /* field[4] = code_type */
  2,   /* field[2] = name */
  1,   /* field[1] = size */
  3,   /* field[3] = uuid */
};
static const ProtobufCIntRange plcrash__crash_report__binary_image__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__binary_image__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.BinaryImage",
  "BinaryImage",
  "Plcrash__CrashReport__BinaryImage",
  "plcrash",
  sizeof(Plcrash__CrashReport__BinaryImage),
  5,
  plcrash__crash_report__binary_image__field_descriptors,
  plcrash__crash_report__binary_image__field_indices_by_name,
  1,  plcrash__crash_report__binary_image__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plcrash__crash_report__exception__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Exception, name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "reason",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Exception, reason),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "frames",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Exception, n_frames),
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Exception, frames),
    &plcrash__crash_report__thread__stack_frame__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__exception__field_indices_by_name[] = {
  2,   /* field[2] = frames */
  0,   /* field[0] = name */
  1,   /* field[1] = reason */
};
static const ProtobufCIntRange plcrash__crash_report__exception__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__exception__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.Exception",
  "Exception",
  "Plcrash__CrashReport__Exception",
  "plcrash",
  sizeof(Plcrash__CrashReport__Exception),
  3,
  plcrash__crash_report__exception__field_descriptors,
  plcrash__crash_report__exception__field_indices_by_name,
  1,  plcrash__crash_report__exception__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plcrash__crash_report__signal__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Signal, name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Signal, code),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__Signal, address),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__signal__field_indices_by_name[] = {
  2,   /* field[2] = address */
  1,   /* field[1] = code */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange plcrash__crash_report__signal__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__signal__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.Signal",
  "Signal",
  "Plcrash__CrashReport__Signal",
  "plcrash",
  sizeof(Plcrash__CrashReport__Signal),
  3,
  plcrash__crash_report__signal__field_descriptors,
  plcrash__crash_report__signal__field_indices_by_name,
  1,  plcrash__crash_report__signal__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plcrash__crash_report__process_info__field_descriptors[6] =
{
  {
    "process_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__ProcessInfo, process_name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "process_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__ProcessInfo, process_id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "process_path",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__ProcessInfo, process_path),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "parent_process_name",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__ProcessInfo, parent_process_name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "parent_process_id",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__ProcessInfo, parent_process_id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "native",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__ProcessInfo, native),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__process_info__field_indices_by_name[] = {
  5,   /* field[5] = native */
  4,   /* field[4] = parent_process_id */
  3,   /* field[3] = parent_process_name */
  1,   /* field[1] = process_id */
  0,   /* field[0] = process_name */
  2,   /* field[2] = process_path */
};
static const ProtobufCIntRange plcrash__crash_report__process_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__process_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.ProcessInfo",
  "ProcessInfo",
  "Plcrash__CrashReport__ProcessInfo",
  "plcrash",
  sizeof(Plcrash__CrashReport__ProcessInfo),
  6,
  plcrash__crash_report__process_info__field_descriptors,
  plcrash__crash_report__process_info__field_indices_by_name,
  1,  plcrash__crash_report__process_info__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plcrash__crash_report__machine_info__field_descriptors[4] =
{
  {
    "model",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__MachineInfo, model),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "processor",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__MachineInfo, processor),
    &plcrash__crash_report__processor__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "processor_count",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__MachineInfo, processor_count),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "logical_processor_count",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport__MachineInfo, logical_processor_count),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__machine_info__field_indices_by_name[] = {
  3,   /* field[3] = logical_processor_count */
  0,   /* field[0] = model */
  1,   /* field[1] = processor */
  2,   /* field[2] = processor_count */
};
static const ProtobufCIntRange plcrash__crash_report__machine_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__machine_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport.MachineInfo",
  "MachineInfo",
  "Plcrash__CrashReport__MachineInfo",
  "plcrash",
  sizeof(Plcrash__CrashReport__MachineInfo),
  4,
  plcrash__crash_report__machine_info__field_descriptors,
  plcrash__crash_report__machine_info__field_indices_by_name,
  1,  plcrash__crash_report__machine_info__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor plcrash__crash_report__field_descriptors[8] =
{
  {
    "system_info",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport, system_info),
    &plcrash__crash_report__system_info__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "application_info",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport, application_info),
    &plcrash__crash_report__application_info__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "threads",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport, n_threads),
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport, threads),
    &plcrash__crash_report__thread__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "binary_images",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport, n_binary_images),
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport, binary_images),
    &plcrash__crash_report__binary_image__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "exception",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport, exception),
    &plcrash__crash_report__exception__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "signal",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport, signal),
    &plcrash__crash_report__signal__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "process_info",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport, process_info),
    &plcrash__crash_report__process_info__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "machine_info",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Plcrash__CrashReport, machine_info),
    &plcrash__crash_report__machine_info__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned plcrash__crash_report__field_indices_by_name[] = {
  1,   /* field[1] = application_info */
  3,   /* field[3] = binary_images */
  4,   /* field[4] = exception */
  7,   /* field[7] = machine_info */
  6,   /* field[6] = process_info */
  5,   /* field[5] = signal */
  0,   /* field[0] = system_info */
  2,   /* field[2] = threads */
};
static const ProtobufCIntRange plcrash__crash_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor plcrash__crash_report__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "plcrash.CrashReport",
  "CrashReport",
  "Plcrash__CrashReport",
  "plcrash",
  sizeof(Plcrash__CrashReport),
  8,
  plcrash__crash_report__field_descriptors,
  plcrash__crash_report__field_indices_by_name,
  1,  plcrash__crash_report__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
const ProtobufCEnumValue plcrash__architecture__enum_values_by_number[7] =
{
  { "X86_32", "PLCRASH__ARCHITECTURE__X86_32", 0 },
  { "X86_64", "PLCRASH__ARCHITECTURE__X86_64", 1 },
  { "ARMV6", "PLCRASH__ARCHITECTURE__ARMV6", 2 },
  { "PPC", "PLCRASH__ARCHITECTURE__PPC", 3 },
  { "PPC64", "PLCRASH__ARCHITECTURE__PPC64", 4 },
  { "ARMV7", "PLCRASH__ARCHITECTURE__ARMV7", 5 },
  { "ARCHITECTURE_UNKNOWN", "PLCRASH__ARCHITECTURE__ARCHITECTURE_UNKNOWN", 6 },
};
static const ProtobufCIntRange plcrash__architecture__value_ranges[] = {
{0, 0},{0, 7}
};
const ProtobufCEnumValueIndex plcrash__architecture__enum_values_by_name[7] =
{
  { "ARCHITECTURE_UNKNOWN", 6 },
  { "ARMV6", 2 },
  { "ARMV7", 5 },
  { "PPC", 3 },
  { "PPC64", 4 },
  { "X86_32", 0 },
  { "X86_64", 1 },
};
const ProtobufCEnumDescriptor plcrash__architecture__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "plcrash.Architecture",
  "Architecture",
  "Plcrash__Architecture",
  "plcrash",
  7,
  plcrash__architecture__enum_values_by_number,
  7,
  plcrash__architecture__enum_values_by_name,
  1,
  plcrash__architecture__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
