/* Copyright (C) 2009-2010 Mikkel Krautz <mikkel@krautz.dk>
   Copyright (c) 2005-2010 Thorvald Natvig, <thorvald@natvig.com>

   All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions
   are met:

   - Redistributions of source code must retain the above copyright notice,
     this list of conditions and the following disclaimer.
   - Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.
   - Neither the name of the Mumble Developers nor the names of its
     contributors may be used to endorse or promote products derived from this
     software without specific prior written permission.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
   ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
   A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
   EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
   PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
   LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include <openssl/x509.h>
#include <openssl/x509v3.h>

#import "Certificate.h"

static int add_ext(X509 * crt, int nid, char *value) {
	X509_EXTENSION *ex;
	X509V3_CTX ctx;
	X509V3_set_ctx_nodb(&ctx);
	X509V3_set_ctx(&ctx, crt, crt, NULL, NULL, 0);
	ex = X509V3_EXT_conf_nid(NULL, &ctx, nid, value);
	if (!ex)
		return 0;
	
	X509_add_ext(crt, ex, -1);
	X509_EXTENSION_free(ex);
	return 1;
}

@interface Certificate (Private)
- (id) initWithDEREncodedCertificate:(NSData *)cert DEREncodedKey:(NSData *)key;
- (void) dealloc;
@end

@implementation Certificate

- (id) initWithDEREncodedCertificate:(NSData *)cert DEREncodedKey:(NSData *)key {
	self = [super init];
	if (self == nil)
		return nil;

	_derCert = [cert retain];
	_derKey = [key retain];

	return self;
}

- (void) dealloc {
	[_derCert release];
	[_derKey release];

	[super dealloc];
}

- (NSData *) derEncodedCertificate {
	return _derCert;
}

- (NSData *) derEncodedKey {
	return _derKey;
}

+ (Certificate *) selfSignedCertificateWithName:(NSString *)aName email:(NSString *)anEmail {
	unsigned char *buf = NULL;

	CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON);

	X509 *x509 = X509_new();
	EVP_PKEY *pkey = EVP_PKEY_new();
	RSA *rsa = RSA_generate_key(2048, RSA_F4, NULL, NULL);
	EVP_PKEY_assign_RSA(pkey, rsa);

	X509_set_version(x509, 2);
	ASN1_INTEGER_set(X509_get_serialNumber(x509),1);
	X509_gmtime_adj(X509_get_notBefore(x509),0);
	X509_gmtime_adj(X509_get_notAfter(x509),60*60*24*365*20);
	X509_set_pubkey(x509, pkey);

	X509_NAME *name = X509_get_subject_name(x509);

	NSString *certName = aName;
	if (certName == nil) {
		// fixme(mkrautz): Desktop Mumble translates this. Do we want to?
		certName = @"Mumble User";
	}

	NSString *certEmail = nil;
	if (anEmail == nil)
		anEmail = @"";
	certEmail = [NSString stringWithFormat:@"email:%@", anEmail];

	X509_NAME_add_entry_by_txt(name, "CN", MBSTRING_ASC, (unsigned char *)[certName UTF8String], -1, -1, 0);
	X509_set_issuer_name(x509, name);
	add_ext(x509, NID_basic_constraints, "critical,CA:FALSE");
	add_ext(x509, NID_ext_key_usage, "clientAuth");
	add_ext(x509, NID_subject_key_identifier, "hash");
	add_ext(x509, NID_netscape_comment, "Generated by Mumble");
	add_ext(x509, NID_subject_alt_name, (char *)[certEmail UTF8String]);

	X509_sign(x509, pkey, EVP_sha1());

	NSMutableData *_derCert = [[NSMutableData alloc] init];
	[_derCert setLength:i2d_X509(x509, NULL)];
	buf = [_derCert mutableBytes];
	i2d_X509(x509, &buf);

	NSMutableData *_derKey = [[NSMutableData alloc] init];
	[_derKey setLength:i2d_PrivateKey(pkey, NULL)];
	buf = [_derKey mutableBytes];
	i2d_PrivateKey(pkey, &buf);

	Certificate *cert = [[Certificate alloc] initWithDEREncodedCertificate:_derCert DEREncodedKey:_derKey];

	X509_free(x509);

	return [cert autorelease];
}

@end
